#!/usr/bin/env npx tsx
/**
 * sync-icons.ts
 *
 * Reads icons.yaml, validates every icon against @iconify-json/material-symbols,
 * and regenerates lib/material-icons.generated.ts.
 *
 * Usage:
 *   npm run sync-icons
 */

import fs from "fs";
import path from "path";
import { load as yamlLoad } from "js-yaml";

// ── paths ────────────────────────────────────────────────────────────────────
const ROOT = path.resolve(__dirname, "..");
const YAML_PATH = path.join(ROOT, "icons.yaml");
const OUTPUT_PATH = path.join(ROOT, "lib", "material-icons.generated.ts");
const ICONIFY_PATH = path.join(
  ROOT,
  "node_modules",
  "@iconify-json",
  "material-symbols",
  "icons.json"
);

// ── types ────────────────────────────────────────────────────────────────────
interface YamlGroup {
  label: string;
  icons: string[];
}

interface YamlFile {
  groups: YamlGroup[];
}

// ── aliases (same as in material-icons.ts) ───────────────────────────────────
// Key: kebab-case name  →  Value: iconify lookup name
const ICON_ALIASES: Record<string, string> = {
  "place": "location-on",
  "people": "group",
  "power": "power-settings-new",
  "wb-cloudy": "cloud",
  "local-grocery-store": "storefront",
  "favorite-border": "favorite",
  "star-border": "star-outline",
  "bookmark-border": "bookmark",
  "local-offer": "sell",
  "emoji-events": "trophy",
  "emoji-emotions": "mood",
};

function toKebab(snake: string): string {
  return snake.replace(/_/g, "-");
}

function iconExistsInPackage(
  iconData: Record<string, unknown>,
  snakeName: string
): boolean {
  const kebab = toKebab(snakeName);
  const lookup = ICON_ALIASES[kebab] ?? kebab;
  return (
    lookup in iconData ||
    `${lookup}-rounded` in iconData ||
    `${lookup}-outline` in iconData
  );
}

// ── main ─────────────────────────────────────────────────────────────────────
function main() {
  // Load iconify icon data
  if (!fs.existsSync(ICONIFY_PATH)) {
    console.error(`ERROR: Could not find ${ICONIFY_PATH}`);
    console.error("Run `npm install` first.");
    process.exit(1);
  }
  const iconData = JSON.parse(fs.readFileSync(ICONIFY_PATH, "utf-8")).icons as Record<string, unknown>;

  // Parse YAML
  if (!fs.existsSync(YAML_PATH)) {
    console.error(`ERROR: Could not find ${YAML_PATH}`);
    process.exit(1);
  }
  const yaml = yamlLoad(fs.readFileSync(YAML_PATH, "utf-8")) as YamlFile;

  if (!yaml?.groups || !Array.isArray(yaml.groups)) {
    console.error("ERROR: icons.yaml must have a top-level `groups` array.");
    process.exit(1);
  }

  // Validate icons and collect errors
  const errors: string[] = [];
  const seen = new Set<string>();

  for (const group of yaml.groups) {
    if (!group.label) {
      errors.push(`A group is missing a 'label' field.`);
    }
    if (!Array.isArray(group.icons)) {
      errors.push(`Group "${group.label}" has no 'icons' array.`);
      continue;
    }
    for (const icon of group.icons) {
      if (seen.has(icon)) {
        errors.push(`Duplicate icon: "${icon}"`);
      }
      seen.add(icon);

      if (!iconExistsInPackage(iconData, icon)) {
        const kebab = toKebab(icon);
        errors.push(
          `Icon "${icon}" (looked up as "${ICON_ALIASES[kebab] ?? kebab}") not found in @iconify-json/material-symbols.`
        );
      }
    }
  }

  if (errors.length > 0) {
    console.error("\nERROR: Icon validation failed:\n");
    errors.forEach((e) => console.error("  ✗ " + e));
    console.error("");
    process.exit(1);
  }

  // Build TypeScript source
  const groupsTs = yaml.groups
    .map((group) => {
      const iconsTs = group.icons
        .map((icon) => `    "${icon}"`)
        .join(",\n");
      return `  {\n    label: "${group.label}",\n    icons: [\n${iconsTs},\n    ],\n  }`;
    })
    .join(",\n");

  const allIcons = yaml.groups.flatMap((g) => g.icons);

  const output = `// AUTO-GENERATED by scripts/sync-icons.ts — do not edit by hand.
// Source of truth: icons.yaml
// Run \`npm run sync-icons\` to regenerate.

export interface IconGroup {
  label: string;
  icons: string[]; // snake_case, matches Flutter _iconMap keys
}

/** All icon groups as defined in icons.yaml. */
export const ICON_GROUPS: IconGroup[] = [
${groupsTs},
];

/** Flat list of all icon names (snake_case) across all groups. */
export const ALL_ICON_NAMES: string[] = [
${allIcons.map((i) => `  "${i}"`).join(",\n")},
];

/**
 * Aliases: when the iconify package uses a different key than the snake_case
 * Flutter name converted to kebab-case.
 * Key: kebab-case  →  Value: iconify lookup name.
 */
export const ICON_ALIASES: Record<string, string> = {
  "place": "location-on",
  "people": "group",
  "power": "power-settings-new",
  "wb-cloudy": "cloud",
  "local-grocery-store": "storefront",
  "favorite-border": "favorite",
  "star-border": "star-outline",
  "bookmark-border": "bookmark",
  "local-offer": "sell",
  "emoji-events": "trophy",
  "emoji-emotions": "mood",
};
`;

  fs.writeFileSync(OUTPUT_PATH, output, "utf-8");

  const totalIcons = allIcons.length;
  const totalGroups = yaml.groups.length;
  console.log(
    `\n✓ Validated and wrote ${totalIcons} icons in ${totalGroups} groups → ${path.relative(ROOT, OUTPUT_PATH)}\n`
  );
}

main();
